### ISSUE TITLE
Pokud zadám špatně číslo, program spadne

### ISSUE THREAD

**Issue by xtompok** [hofrajtm/zkouska#7]
Výjimky jsme se ošetřovat už učili.

**Comment by hofrajtm** [comment]
Já fakt zkoušel všechny možný kombinace a fungovalo všechno. :)

**Comment by xtompok** [comment]
Převod čísla z arabských číslic na římské.
Zadejte číslo:ěščěšč\
Exception in thread "main" java.lang.NumberFormatException: For input string: "ěščěšč\"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at prevodcisel.PrevodCisel.readInt(PrevodCisel.java:358)
	at prevodcisel.PrevodCisel.main(PrevodCisel.java:38)
/home/jethro/Dokumenty/prifuk/uvod-do-prg/zkouska/martin_hofrajtr/nbproject/build-impl.xml:1040: The following error occurred while executing this line:
/home/jethro/Dokumenty/prifuk/uvod-do-prg/zkouska/martin_hofrajtr/nbproject/build-impl.xml:805: Java returned: 1
BUILD FAILED (total time: 1 second)

**Comment by hofrajtm** [comment]
Opraveno.
